import type { Category } from '../types/expense';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'food',
    name: 'Ăn uống & Cà phê',
    icon: 'Utensils',
    color: '#f97316',
    bgLight: '#ffedd5',
    budgetLimit: 4500000,
  },
  {
    id: 'housing',
    name: 'Nhà cửa & Hóa đơn',
    icon: 'Home',
    color: '#3b82f6',
    bgLight: '#dbeafe',
    budgetLimit: 5000000,
  },
  {
    id: 'transport',
    name: 'Di chuyển & Xăng xe',
    icon: 'Car',
    color: '#eab308',
    bgLight: '#fef9c3',
    budgetLimit: 1500000,
  },
  {
    id: 'shopping',
    name: 'Mua sắm & Đồ dùng',
    icon: 'ShoppingBag',
    color: '#ec4899',
    bgLight: '#fce7f3',
    budgetLimit: 2500000,
  },
  {
    id: 'entertainment',
    name: 'Giải trí & Du lịch',
    icon: 'Film',
    color: '#8b5cf6',
    bgLight: '#ede9fe',
    budgetLimit: 1800000,
  },
  {
    id: 'health',
    name: 'Sức khỏe & Y tế',
    icon: 'HeartPulse',
    color: '#ef4444',
    bgLight: '#fee2e2',
    budgetLimit: 1000000,
  },
  {
    id: 'education',
    name: 'Giáo dục & Bản thân',
    icon: 'GraduationCap',
    color: '#06b6d4',
    bgLight: '#cffafe',
    budgetLimit: 1200000,
  },
  {
    id: 'family',
    name: 'Gia đình & Thú cưng',
    icon: 'Users',
    color: '#10b981',
    bgLight: '#d1fae5',
    budgetLimit: 1500000,
  },
  {
    id: 'gifts',
    name: 'Hiếu hỷ & Quà tặng',
    icon: 'Gift',
    color: '#f43f5e',
    bgLight: '#ffe4e6',
    budgetLimit: 1000000,
  },
  {
    id: 'other',
    name: 'Chi phí khác',
    icon: 'MoreHorizontal',
    color: '#64748b',
    bgLight: '#f1f5f9',
    budgetLimit: 1000000,
  },
];
